# Generated by Django 4.1 on 2022-08-31 13:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000)])),
                ('phone', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000000000)])),
                ('address', models.CharField(default='', max_length=60)),
                ('city', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderEmail', models.EmailField(max_length=20)),
                ('cart', models.JSONField()),
                ('orderAdd', models.CharField(default='', max_length=60)),
                ('Ordercity', models.CharField(default='', max_length=20)),
                ('Orderstate', models.CharField(default='', max_length=20)),
                ('Orderphone', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000000000)])),
                ('Orderprice', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('Orderotp', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000)])),
                ('OrderStatus', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2)])),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('orderDevice', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('prodImg', models.ImageField(default='', null=True, upload_to='media')),
                ('desc', models.CharField(max_length=400)),
                ('ratings', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('category', models.CharField(max_length=50)),
                ('viewTD', models.IntegerField(default=0)),
                ('viewMonth', models.IntegerField(default=0)),
                ('viewWeek', models.IntegerField(default=0)),
                ('viewToday', models.IntegerField(default=0)),
                ('soldTD', models.IntegerField(default=0)),
                ('soldMonth', models.IntegerField(default=0)),
                ('soldWeek', models.IntegerField(default=0)),
                ('soldToday', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=300)),
                ('timezone', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint.review')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
